// Generated by gencpp from file servicio/cmd_mover.msg
// DO NOT EDIT!


#ifndef SERVICIO_MESSAGE_CMD_MOVER_H
#define SERVICIO_MESSAGE_CMD_MOVER_H

#include <ros/service_traits.h>


#include <servicio/cmd_moverRequest.h>
#include <servicio/cmd_moverResponse.h>


namespace servicio
{

struct cmd_mover
{

typedef cmd_moverRequest Request;
typedef cmd_moverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cmd_mover
} // namespace servicio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::servicio::cmd_mover > {
  static const char* value()
  {
    return "0d7c1320405ff716cbb9ed56b1e4bf4b";
  }

  static const char* value(const ::servicio::cmd_mover&) { return value(); }
};

template<>
struct DataType< ::servicio::cmd_mover > {
  static const char* value()
  {
    return "servicio/cmd_mover";
  }

  static const char* value(const ::servicio::cmd_mover&) { return value(); }
};


// service_traits::MD5Sum< ::servicio::cmd_moverRequest> should match 
// service_traits::MD5Sum< ::servicio::cmd_mover > 
template<>
struct MD5Sum< ::servicio::cmd_moverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::servicio::cmd_mover >::value();
  }
  static const char* value(const ::servicio::cmd_moverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::servicio::cmd_moverRequest> should match 
// service_traits::DataType< ::servicio::cmd_mover > 
template<>
struct DataType< ::servicio::cmd_moverRequest>
{
  static const char* value()
  {
    return DataType< ::servicio::cmd_mover >::value();
  }
  static const char* value(const ::servicio::cmd_moverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::servicio::cmd_moverResponse> should match 
// service_traits::MD5Sum< ::servicio::cmd_mover > 
template<>
struct MD5Sum< ::servicio::cmd_moverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::servicio::cmd_mover >::value();
  }
  static const char* value(const ::servicio::cmd_moverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::servicio::cmd_moverResponse> should match 
// service_traits::DataType< ::servicio::cmd_mover > 
template<>
struct DataType< ::servicio::cmd_moverResponse>
{
  static const char* value()
  {
    return DataType< ::servicio::cmd_mover >::value();
  }
  static const char* value(const ::servicio::cmd_moverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICIO_MESSAGE_CMD_MOVER_H
